# Generated by Django 4.2.3 on 2023-07-24 02:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="category",
        ),
        migrations.CreateModel(
            name="BlogPostPageCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select categories for the blog post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_post_categories",
                        to="blog.blogpostpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
