# Generated by Django 4.2.3 on 2023-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blogpostpage_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="author",
        ),
    ]
