# Generated by Django 4.2.3 on 2023-07-30 14:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_blogpostpage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Write a subtitle for the blog post. This will be displayed in the blog post overview.",
                null=True,
                verbose_name="Subtitle",
            ),
        ),
    ]
