# Generated by Django 4.2.3 on 2023-07-30 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_blogpostpage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="highlighted_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.blogpostpage",
            ),
        ),
    ]
